model:
  input_dim: 5          # Number of input features
  hidden_dim: 64
  num_layers: 2
  output_dim: 1         # Predicting 1 value (e.g. next closing price)

train_data:
  X_path: data/processed/train_X.pt
  Y_path: data/processed/train_Y.pt

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 30
  save_every: 10
  save_dir: models/checkpoints
